# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install module...
      run: npm install
    - name: Install Mocha in globale....
      run: npm install --global mocha --save
    - name: Test of deploy
      run: set NODE_ENV=test && ./node_modules/.bin/nyc  --reporter=text --reporter=lcov mocha test/apitest.js --exit -paramMySQL -${{secrets.BDD_IP_TEST}} -${{secrets.BDD_USERNAME_TEST}}  -${{secrets.BDD_PASSWORD_TEST}}  -${{secrets.BDD_DATABASE_NAME_TEST}}  
      env:
        NODE_ENV: test   
    - name: Scan SonarCloud 
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: /github/workspace/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Deploy to ASUSTOR server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST_ASUSTOR }}
        username: ${{ secrets.REMOTE_USER_ASUSTOR }}
        key: ${{ secrets.SSH_PRIVATE_KEY_ASUSTOR }}
        script: cd ${{ secrets.REMOTE_TARGET_ASUSTOR }} && git fetch --all && git pull  && npm install && sh reload.sh


