# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install --global mocha --save
    - run: set NODE_ENV=test && ./node_modules/.bin/nyc  --reporter=text --reporter=lcov mocha test/apitest.js --exit -paramMySQL -${{secrets.BDD_IP_TEST}} -${{secrets.BDD_USERNAME_TEST}}  -${{secrets.BDD_PASSWORD_TEST}}  -${{secrets.BDD_DATABASE_NAME_TEST}}
    #- run: readlink -f /home/runner/work/shindra-online-api/shindra-online-api/coverage/lcov.info     
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: /github/workspace/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Deploy to ASUSTOR server
      uses: easingthemes/ssh-deploy@v2.0.7
      #env:
        #SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        #ARGS: "-rltgoDzvO"
        #SOURCE: "dist/"
        #REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        #REMOTE_USER: ${{ secrets.REMOTE_USER }}
        #TARGET: ${{ secrets.REMOTE_TARGET }}
